@ERP_Finance_HostAddress = http://localhost:5262

//Create Product
POST {{ERP_Finance_HostAddress}}/api/product
Content-Type: application/json
{
  "name": "Arroz Integral",
  "description": "Arroz Integral",
  "price": 29.90,
  "category": 1,
  "brandName": "Tio Pedro",
  "weightOrVolume": 5,
  "measureType": 1
}

###
 
//GetAll Product
GET {{ERP_Finance_HostAddress}}/api/product

###

//Search By Name Product
GET {{ERP_Finance_HostAddress}}/api/Product/search?name=arroz

###

//GetById Product
GET {{ERP_Finance_HostAddress}}/api/product/705f58e3-6095-4ac0-ac1b-91921bc80a38

###

//Update Product
PATCH {{ERP_Finance_HostAddress}}/api/product/705f58e3-6095-4ac0-ac1b-91921bc80a38
Content-Type: application/json
{
  "price": 30.00
}

###

//Delete Product
DELETE {{ERP_Finance_HostAddress}}/api/product/705f58e3-6095-4ac0-ac1b-91921bc80a38

###

//HealthCheck
GET {{ERP_Finance_HostAddress}}/health

###

//Create OrderItem
POST {{ERP_Finance_HostAddress}}/api/orderItem
Content-Type: application/json
{
  "orderId": "cdd357fe-1e79-420c-b6b6-95ea3e3a4257",
  "productId": "00e667cc-356c-4962-98a7-de5c0f1e6403",
  "quantity": 2.5
}

###
//Get OrderItem
GET {{ERP_Finance_HostAddress}}/api/orderItem/be49d270-665a-468b-9870-02adeeef5145
