@ERP_Finance_HostAddress = http://localhost:5262

//Create
POST {{ERP_Finance_HostAddress}}/api/product
Content-Type: application/json
{
  "name": "Arroz Integral",
  "description": "Arroz Integral",
  "price": 29.90,
  "category": 1,
  "brandName": "Tio Pedro",
  "weightOrVolume": 5,
  "measureType": 1
}

###

//GetAll
GET {{ERP_Finance_HostAddress}}/api/product

###

//Search By Name
GET {{ERP_Finance_HostAddress}}/api/Product/search?name=arroz

###

//GetById
GET {{ERP_Finance_HostAddress}}/api/product/705f58e3-6095-4ac0-ac1b-91921bc80a38

###

//Update
PATCH {{ERP_Finance_HostAddress}}/api/product/705f58e3-6095-4ac0-ac1b-91921bc80a38
Content-Type: application/json
{
  "price": 30.00
}

###

//Delete
DELETE {{ERP_Finance_HostAddress}}/api/product/705f58e3-6095-4ac0-ac1b-91921bc80a38

###

//HealthCheck
GET {{ERP_Finance_HostAddress}}/health